version: "1.1"

services:
  node:
    container_name: puppyhome_backend
    restart: always
    image: node:16.10.0
    ports:
      - 3007:3007
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks:
      - puppyhome_network
    # PRODUCTION
    command: bash -c "npm install && npm run start:prod"
    # DEVELOPMENT
    # command: bash -c "npm install && npm run dev"

networks:
  puppyhome_network:
    driver: bridge
